apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mentor-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-mentor-api
  template:
    metadata:
      labels:
        app: ai-mentor-api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/ai-mentor-api:${TAG}
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-mentor-secrets
              key: database-url
        - name: REDIS_URL
          value: redis://ai-mentor-redis:6379
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-mentor-api
spec:
  selector:
    app: ai-mentor-api
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP