apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ai-mentor-redis
spec:
  serviceName: ai-mentor-redis
  replicas: 1
  selector:
    matchLabels:
      app: ai-mentor-redis
  template:
    metadata:
      labels:
        app: ai-mentor-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ai-mentor-redis
spec:
  selector:
    app: ai-mentor-redis
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None